create extension if not exists pgcrypto;

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title_cs text,
  title_en text,
  description_cs text,
  description_en text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.topics (
  slug,
  title_cs,
  title_en,
  description_cs,
  description_en,
  image_url,
  sort_order
)
values (
  'adamek',
  'Adámek',
  'Adamek',
  'Adamův playground pro malé hry, objevování, pexeso a další nápady, které si časem najdou vlastní místo.',
  'Adam''s playground for small games, discovery, memory cards, and future ideas that deserve their own place.',
  'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?auto=format&fit=crop&w=1200&q=80',
  10
)
on conflict (slug) do update set
  title_cs = excluded.title_cs,
  title_en = excluded.title_en,
  description_cs = excluded.description_cs,
  description_en = excluded.description_en,
  image_url = excluded.image_url;

create table if not exists public.adamek_memory_themes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  images text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists adamek_memory_themes_name_idx
  on public.adamek_memory_themes (name);

alter table public.adamek_memory_themes enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.adamek_memory_themes to anon, authenticated;

drop policy if exists "Allow public read adamek memory themes" on public.adamek_memory_themes;

create policy "Allow public read adamek memory themes"
  on public.adamek_memory_themes
  for select
  using (true);

insert into public.adamek_memory_themes (name, images)
select
  'Jídlo',
  array[
    '/adamek/food/jablko.svg',
    '/adamek/food/banan.svg',
    '/adamek/food/jahoda.svg',
    '/adamek/food/mrkev.svg',
    '/adamek/food/syr.svg',
    '/adamek/food/pizza.svg',
    '/adamek/food/zmrzlina.svg',
    '/adamek/food/dort.svg',
    '/adamek/food/kobliha.svg',
    '/adamek/food/meloun.svg',
    '/adamek/food/hrozny.svg',
    '/adamek/food/citron.svg',
    '/adamek/food/hruska.svg',
    '/adamek/food/rajce.svg',
    '/adamek/food/brambora.svg',
    '/adamek/food/chleba.svg',
    '/adamek/food/croissant.svg',
    '/adamek/food/vejce.svg',
    '/adamek/food/palacinka.svg',
    '/adamek/food/susenka.svg',
    '/adamek/food/cokolada.svg',
    '/adamek/food/popcorn.svg',
    '/adamek/food/med.svg',
    '/adamek/food/salat.svg',
    '/adamek/food/tacos.svg',
    '/adamek/food/hamburger.svg',
    '/adamek/food/hranolky.svg',
    '/adamek/food/ryba.svg',
    '/adamek/food/sushi.svg',
    '/adamek/food/kukurice.svg'
  ]
where not exists (
  select 1 from public.adamek_memory_themes where lower(name) = lower('Jídlo')
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'adamek-memory',
  'adamek-memory',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'image/svg+xml']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Allow public read adamek memory images" on storage.objects;

create policy "Allow public read adamek memory images"
  on storage.objects
  for select
  using (bucket_id = 'adamek-memory');
