create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  nickname text not null unique,
  points integer not null default 0,
  completed_quizzes integer not null default 0,
  badges text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leaderboard
  add column if not exists completed_quizzes integer not null default 0,
  add column if not exists badges text[] not null default '{}',
  add column if not exists updated_at timestamptz not null default now();

create index if not exists leaderboard_points_idx
  on public.leaderboard (points desc);

alter table public.leaderboard enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.leaderboard to anon, authenticated;
grant usage, select on sequence public.leaderboard_id_seq to anon, authenticated;

drop policy if exists "Allow public read leaderboard" on public.leaderboard;
drop policy if exists "Allow public insert leaderboard" on public.leaderboard;
drop policy if exists "Allow public update leaderboard" on public.leaderboard;

create policy "Allow public read leaderboard"
  on public.leaderboard
  for select
  using (true);

create policy "Allow public insert leaderboard"
  on public.leaderboard
  for insert
  with check (true);

create policy "Allow public update leaderboard"
  on public.leaderboard
  for update
  using (true)
  with check (true);
