create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  topic_slug text not null,
  difficulty text not null default 'easy' check (difficulty in ('easy', 'medium', 'hard')),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('A', 'B', 'C', 'D')),
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quiz_questions_topic_order_idx
  on public.quiz_questions (topic_slug, sort_order);

create index if not exists quiz_questions_topic_difficulty_order_idx
  on public.quiz_questions (topic_slug, difficulty, sort_order);

alter table public.quiz_questions enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.quiz_questions to anon, authenticated;
grant usage, select on sequence public.quiz_questions_id_seq to anon, authenticated;

-- For a private family admin, replace these policies with authenticated-only rules.
create policy "Allow public read quiz questions"
  on public.quiz_questions for select
  using (true);

create policy "Allow public insert quiz questions"
  on public.quiz_questions for insert
  with check (true);

create policy "Allow public update quiz questions"
  on public.quiz_questions for update
  using (true)
  with check (true);

create policy "Allow public delete quiz questions"
  on public.quiz_questions for delete
  using (true);
