insert into public.quiz_questions
  (topic_slug, question, option_a, option_b, option_c, option_d, correct_option, sort_order)
values
  ('animals', 'Které zvíře je známé jako král džungle?', 'Tygr', 'Lev', 'Slon', 'Žirafa', 'B', 1),
  ('animals', 'Který pták neumí létat?', 'Orel', 'Tučňák', 'Sova', 'Čáp', 'B', 2),
  ('animals', 'Kolik nohou má pavouk?', '6', '8', '10', '12', 'B', 3),
  ('animals', 'Které zvíře dává mléko lidem nejčastěji?', 'Kráva', 'Liška', 'Jelen', 'Ježek', 'A', 4),
  ('animals', 'Které zvíře má chobot?', 'Nosorožec', 'Slon', 'Hroch', 'Medvěd', 'B', 5),
  ('animals', 'Jak se jmenuje mládě psa?', 'Kotě', 'Hříbě', 'Štěně', 'Tele', 'C', 6),
  ('animals', 'Které zvíře se umí stočit do klubíčka?', 'Ježek', 'Kůň', 'Kapr', 'Vlk', 'A', 7),
  ('animals', 'Co jí panda nejraději?', 'Bambus', 'Sýr', 'Mrkev', 'Houby', 'A', 8),
  ('animals', 'Které zvíře mění barvu podle okolí?', 'Chameleon', 'Koza', 'Holub', 'Křeček', 'A', 9),
  ('animals', 'Které zvíře je největší na světě?', 'Slon africký', 'Žralok bílý', 'Plejtvák obrovský', 'Žirafa', 'C', 10),

  ('world', 'Na kterém kontinentu leží Česká republika?', 'Asie', 'Evropa', 'Afrika', 'Austrálie', 'B', 1),
  ('world', 'Které město je hlavní město Francie?', 'Řím', 'Berlín', 'Paříž', 'Madrid', 'C', 2),
  ('world', 'Který oceán je největší?', 'Tichý', 'Atlantský', 'Indický', 'Severní ledový', 'A', 3),
  ('world', 'Která země má tvar boty?', 'Itálie', 'Norsko', 'Egypt', 'Kanada', 'A', 4),
  ('world', 'Jak se jmenuje nejvyšší hora světa?', 'Mont Blanc', 'Kilimandžáro', 'Mount Everest', 'Sněžka', 'C', 5),
  ('world', 'Kde najdeme pyramidy v Gíze?', 'V Egyptě', 'V Peru', 'V Řecku', 'V Japonsku', 'A', 6),
  ('world', 'Která řeka protéká Prahou?', 'Labe', 'Vltava', 'Morava', 'Dunaj', 'B', 7),
  ('world', 'Který jazyk se nejčastěji používá v Brazílii?', 'Španělština', 'Portugalština', 'Angličtina', 'Francouzština', 'B', 8),
  ('world', 'Který světadíl je nejchladnější?', 'Afrika', 'Antarktida', 'Evropa', 'Jižní Amerika', 'B', 9),
  ('world', 'Která planeta je náš domov?', 'Mars', 'Venuše', 'Země', 'Jupiter', 'C', 10),

  ('body', 'Který orgán pumpuje krev?', 'Plíce', 'Srdce', 'Žaludek', 'Mozek', 'B', 1),
  ('body', 'Čím dýcháme?', 'Plícemi', 'Koleny', 'Vlasy', 'Ušima', 'A', 2),
  ('body', 'Kolik máme obvykle dospělých zubů?', '12', '20', '32', '44', 'C', 3),
  ('body', 'Který smysl používáme očima?', 'Čich', 'Sluch', 'Zrak', 'Chuť', 'C', 4),
  ('body', 'Co chrání mozek?', 'Lebka', 'Žebra', 'Loket', 'Pata', 'A', 5),
  ('body', 'K čemu slouží kosti?', 'Drží tělo a chrání orgány', 'Barví vlasy', 'Vyrábí sliny', 'Vidí ve tmě', 'A', 6),
  ('body', 'Kde máme chuťové pohárky?', 'Na jazyku', 'Na rameni', 'Na zádech', 'Na patě', 'A', 7),
  ('body', 'Co nám pomáhá slyšet?', 'Uši', 'Kolena', 'Prsty', 'Obočí', 'A', 8),
  ('body', 'Jaký sval používáme při úsměvu?', 'Svaly v obličeji', 'Svaly v chodidle', 'Svaly v lokti', 'Svaly v koleni', 'A', 9),
  ('body', 'Proč pijeme vodu?', 'Aby tělo fungovalo', 'Aby zmizely boty', 'Aby rostly kameny', 'Aby se zastavil čas', 'A', 10),

  ('ocean', 'Která ryba je známá z korálových útesů a má oranžové pruhy?', 'Klaun očkatý', 'Kapr', 'Štika', 'Sumec', 'A', 1),
  ('ocean', 'Čím dýchají ryby?', 'Žábrami', 'Listy', 'Křídly', 'Srstí', 'A', 2),
  ('ocean', 'Který mořský tvor má osm chapadel?', 'Chobotnice', 'Delfín', 'Krab', 'Žralok', 'A', 3),
  ('ocean', 'Které zvíře si nosí krunýř?', 'Mořská želva', 'Medúza', 'Tuňák', 'Rejnok', 'A', 4),
  ('ocean', 'Co je korál?', 'Mořský živočich', 'Druh mraku', 'Horský kámen', 'Pouštní strom', 'A', 5),
  ('ocean', 'Který savec žije v moři a je velmi chytrý?', 'Delfín', 'Vrabec', 'Kůň', 'Ještěrka', 'A', 6),
  ('ocean', 'Jak chutná mořská voda?', 'Slaně', 'Sladce', 'Kysele', 'Hořce jako kakao', 'A', 7),
  ('ocean', 'Který tvor má klepeta?', 'Krab', 'Sardinka', 'Medúza', 'Kosatka', 'A', 8),
  ('ocean', 'Co způsobuje příliv a odliv?', 'Hlavně Měsíc', 'Pouze vítr', 'Sníh', 'Semafory', 'A', 9),
  ('ocean', 'Který živočich může být nebezpečný díky žahavým chapadlům?', 'Medúza', 'Tučňák', 'Mořský koník', 'Treska', 'A', 10),

  ('dinosaurs', 'Který dinosaurus měl obrovské zuby a krátké ruce?', 'Tyrannosaurus rex', 'Triceratops', 'Stegosaurus', 'Brachiosaurus', 'A', 1),
  ('dinosaurs', 'Který dinosaurus měl tři rohy?', 'Triceratops', 'Velociraptor', 'Diplodocus', 'Ankylosaurus', 'A', 2),
  ('dinosaurs', 'Co jedl Brachiosaurus?', 'Rostliny', 'Auta', 'Ryby z konzervy', 'Kameny', 'A', 3),
  ('dinosaurs', 'Jak se jmenují zkamenělé pozůstatky?', 'Fosilie', 'Kompasy', 'Drahokamy', 'Mapy', 'A', 4),
  ('dinosaurs', 'Kdo zkoumá dinosaury?', 'Paleontolog', 'Pekař', 'Pilot', 'Houslista', 'A', 5),
  ('dinosaurs', 'Který dinosaurus měl desky na zádech?', 'Stegosaurus', 'Spinosaurus', 'Iguanodon', 'Allosaurus', 'A', 6),
  ('dinosaurs', 'Žili dinosauři dávno před lidmi?', 'Ano', 'Ne', 'Jen v zimě', 'Jen v Praze', 'A', 7),
  ('dinosaurs', 'Který dinosaurus měl dlouhý krk?', 'Diplodocus', 'Velociraptor', 'T. rex', 'Triceratops', 'A', 8),
  ('dinosaurs', 'Co znamená, že byl dinosaurus masožravec?', 'Jedl maso', 'Jedl jen listí', 'Pil jen mléko', 'Uměl létat v raketě', 'A', 9),
  ('dinosaurs', 'Který dinosaurus bývá zobrazován s klubem na ocase?', 'Ankylosaurus', 'Pteranodon', 'Compsognathus', 'Parasaurolophus', 'A', 10),

  ('space', 'Která hvězda je nejblíže Zemi?', 'Slunce', 'Polárka', 'Sirius', 'Vega', 'A', 1),
  ('space', 'Na které planetě žijeme?', 'Země', 'Mars', 'Saturn', 'Merkur', 'A', 2),
  ('space', 'Která planeta je známá prstenci?', 'Saturn', 'Venuše', 'Mars', 'Uran', 'A', 3),
  ('space', 'Jak se jmenuje přirozená družice Země?', 'Měsíc', 'Kometa', 'Pluto', 'Meteor', 'A', 4),
  ('space', 'Která planeta je červená?', 'Mars', 'Neptun', 'Jupiter', 'Země', 'A', 5),
  ('space', 'Čím letí astronaut do vesmíru?', 'Raketou', 'Ponorkou', 'Traktorem', 'Koloběžkou', 'A', 6),
  ('space', 'Co je galaxie?', 'Obrovská skupina hvězd', 'Druh ovoce', 'Sportovní míč', 'Kniha', 'A', 7),
  ('space', 'Jak se nazývá padající světelná stopa na obloze?', 'Meteor', 'Duha', 'Mrak', 'Blesk v láhvi', 'A', 8),
  ('space', 'Je Slunce planeta?', 'Ne, je to hvězda', 'Ano', 'Je to měsíc', 'Je to kometa', 'A', 9),
  ('space', 'Co potřebuje astronaut venku z lodi?', 'Skafandr', 'Plavky', 'Brusle', 'Deštník', 'A', 10),

  ('insects', 'Kolik nohou má hmyz?', '6', '8', '4', '10', 'A', 1),
  ('insects', 'Který hmyz vyrábí med?', 'Včela', 'Mravenec', 'Komár', 'Moucha', 'A', 2),
  ('insects', 'Co se z housenky stane?', 'Motýl', 'Ryba', 'Kámen', 'Žába', 'A', 3),
  ('insects', 'Který hmyz žije v mraveništi?', 'Mravenec', 'Vosa', 'Vážka', 'Kobylka', 'A', 4),
  ('insects', 'Který hmyz svítí?', 'Světluška', 'Brouk bramborák', 'Moucha', 'Včela', 'A', 5),
  ('insects', 'Jak se jmenuje červený brouček s tečkami?', 'Beruška', 'Sršeň', 'Komár', 'Cvrček', 'A', 6),
  ('insects', 'Který hmyz skáče a cvrká?', 'Cvrček', 'Včela', 'Motýl', 'Moucha', 'A', 7),
  ('insects', 'Co sbírá včela z květů?', 'Nektar', 'Sůl', 'Písek', 'Sníh', 'A', 8),
  ('insects', 'Který hmyz má velká barevná křídla?', 'Motýl', 'Mravenec', 'Komár', 'Blecha', 'A', 9),
  ('insects', 'Je pavouk hmyz?', 'Ne', 'Ano', 'Jen malý', 'Jen v létě', 'A', 10),

  ('plants', 'Co rostliny potřebují ke světlu?', 'Slunce', 'Televizi', 'Boty', 'Klíče', 'A', 1),
  ('plants', 'Který strom má žaludy?', 'Dub', 'Bříza', 'Smrk', 'Jabloň', 'A', 2),
  ('plants', 'Z čeho vyroste rostlina?', 'Semínko', 'Kamínek', 'Sklenička', 'Knoflík', 'A', 3),
  ('plants', 'Co mají jehličnany místo listů?', 'Jehličí', 'Peří', 'Srst', 'Šupiny', 'A', 4),
  ('plants', 'Která rostlina dává jablka?', 'Jabloň', 'Růže', 'Tulipán', 'Kaktus', 'A', 5),
  ('plants', 'Co nasávají kořeny z půdy?', 'Vodu a živiny', 'Hudbu', 'Barvu oblohy', 'Světlo lampy', 'A', 6),
  ('plants', 'Která část rostliny bývá barevná a voní?', 'Květ', 'Kořen', 'Kůra', 'Pecka', 'A', 7),
  ('plants', 'Který strom je vánočním stromkem nejčastěji?', 'Smrk', 'Palma', 'Banánovník', 'Bambus', 'A', 8),
  ('plants', 'Co vyrábí rostliny pro dýchání lidí?', 'Kyslík', 'Písek', 'Kov', 'Mléko', 'A', 9),
  ('plants', 'Která rostlina má trny a často krásně voní?', 'Růže', 'Pampeliška', 'Tráva', 'Mech', 'A', 10),

  ('records', 'Které zvíře je nejrychlejší na souši?', 'Gepard', 'Želva', 'Slon', 'Kočka domácí', 'A', 1),
  ('records', 'Která hora je nejvyšší na světě?', 'Mount Everest', 'Sněžka', 'Etna', 'Olymp', 'A', 2),
  ('records', 'Který oceán je největší?', 'Tichý oceán', 'Indický oceán', 'Atlantský oceán', 'Jižní oceán', 'A', 3),
  ('records', 'Které zvíře je největší?', 'Plejtvák obrovský', 'Slon', 'Žirafa', 'Hroch', 'A', 4),
  ('records', 'Který pták je největší?', 'Pštros', 'Vrabec', 'Tučňák císařský', 'Orel', 'A', 5),
  ('records', 'Která poušť je největší horká poušť?', 'Sahara', 'Gobi', 'Kalahari', 'Atacama', 'A', 6),
  ('records', 'Který savec má nejdelší krk?', 'Žirafa', 'Kůň', 'Velbloud', 'Lama', 'A', 7),
  ('records', 'Která planeta je největší ve Sluneční soustavě?', 'Jupiter', 'Země', 'Mars', 'Venuše', 'A', 8),
  ('records', 'Který strom může být velmi vysoký rekordman?', 'Sekvoje', 'Jabloň', 'Třešeň', 'Keř rybízu', 'A', 9),
  ('records', 'Která řeka bývá uváděna mezi nejdelšími na světě?', 'Nil', 'Vltava', 'Sázava', 'Ohře', 'A', 10);
