create table if not exists public.site_settings (
  id text primary key default 'main',
  brand_label text not null default 'Havelka Vitek',
  eyebrow_cs text not null default 'osobni mapa',
  eyebrow_en text not null default 'personal map',
  headline_cs text not null default 'Veci, ktere me drzi v pohybu.',
  headline_en text not null default 'Things that keep me moving.',
  intro_cs text not null default 'Interaktivni sit zajmu, prace a remesel. Vyber uzel a otevri detail.',
  intro_en text not null default 'An interactive network of interests, work, and craft. Pick a node to open the detail.',
  login_label text not null default 'Login',
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id)
values ('main')
on conflict (id) do nothing;

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title_cs text,
  title_en text,
  description_cs text,
  description_en text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.topics
  add column if not exists title_cs text,
  add column if not exists title_en text,
  add column if not exists description_cs text,
  add column if not exists description_en text,
  add column if not exists image_url text,
  add column if not exists sort_order integer not null default 0;

create index if not exists topics_sort_order_idx
  on public.topics (sort_order);

grant usage on schema public to anon, authenticated;
grant select on public.site_settings to anon, authenticated;
grant all on public.site_settings to service_role;
grant select on public.topics to anon, authenticated;
grant all on public.topics to service_role;
grant usage, select on sequence public.topics_id_seq to service_role;

create table if not exists public.section_posts (
  id bigint generated by default as identity primary key,
  topic_slug text not null,
  title text not null,
  body text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists section_posts_topic_order_idx
  on public.section_posts (topic_slug, sort_order);

grant select on public.section_posts to anon, authenticated;
grant all on public.section_posts to service_role;
grant usage, select on sequence public.section_posts_id_seq to service_role;

-- Server-side admin mutations should use SUPABASE_SERVICE_ROLE_KEY.
